### ISSUE TITLE
Does not create Plugin Library

### ISSUE THREAD

**Issue by kookma** [inmysocks/PluginDevelopment#1]
To reproduce

1. Install the PluginDevelopment as described in readme.md
2. It has its own Tiddlywiki under Tiddlywiki5 folder
3. Run Setup.sh
4. Run MakePlugin.sh to create a plugin
5. Add one macro to new plugin to display Hi World...
6. Create a Test Wiki, add the new plugin  to test and it works fine
7. Run MakePluginLibrary.sh
8. A new PluginLibrary/output folder created which has index.html and recipes/library folder and inside that a tiddler.json and nothing else

**Comment by kookma** [comment]
@inmysocks 
I am on Windows 10

**Comment by inmysocks** [comment]
The error you had running setup.sh means that this won't work, at the moment this is a problem with setup.sh and sed.
