### ISSUE TITLE
Error on folders with space in name

### ISSUE THREAD

**Issue by kookma** [inmysocks/PluginDevelopment#3]
Assume you put the PluginDevelopment in a folder like below

C:/Jed Carty/PluginDevelopment

and then run the Setup.sh

It creates new folder asC:/Jed again!

When I removed the space and use the folder like

`C:/JedCarty/PluginDevelopment`
it works fine. Note to space in `Jed Carty`

**Comment by inmysocks** [comment]
I just push a fix for this
