### ISSUE TITLE
[BUG] The index.html of plugin library seems incorrect

### ISSUE THREAD

**Issue by kookma** [inmysocks/PluginDevelopment#6]
After successful creating plugins and testing them, I create plugin library using:

`./MakePluginLibrary.sh` and the output directory with library was created. It has 

- index.html
- recipes/library

So everything was successful! 
Then I used github pages to host static files, and did all configuration
I used the library in tiddlywiki.com but I noticed library is empty.

I investigated the index.html and I see the below

```
var assetList = ;

/*\
title: $:/plugins/tiddlywiki/pluginlibrary/libraryserver.js
type: application/javascript
module-type: library

A simple HTTP-over-window.postMessage implementation of a standard TiddlyWeb-compatible server. It uses real HTTP to load the individual tiddler JSON files.

\*/
(function(){
```

While this should be the list of plugins

**Comment by inmysocks** [comment]
I found where this comes from, there is a part of the plugin library that is hardcoded to use $:/UpgradeLibrary and I changed that in the demo and didn't do enough testing. For now the solution is to change it back in the demo, I will see if I can find a quick way to fix the plugin for the next tiddlywiki release.

**Comment by kookma** [comment]
Thank you Jed! I will try the solution you proposed.

**Comment by inmysocks** [comment]
I pushed a fix

**Comment by kookma** [comment]
Thank you. I update my local repo and will let you know the results.

**Comment by kookma** [comment]
Hi @inmysocks 
I tested the new fix. It works fine!

Many thanks
